### ISSUE TITLE
Change DM to twitter

### ISSUE THREAD

**Issue by mittalyashu** [pairhub/pairhub#44]
Not everyone uses Gitter as a communication tool, maybe Twitter DMs would be a better choice.

**Comment by gustavlrsn** [comment]
Good idea. I kind of like the idea of having an internal DM system eventually (#19).

But since I switched out the Gitter community for a Slack community, maybe we should just remove the DM button for now. With markdown support, people could just link to wherever they would like to be contacted also :)
